name: Allure report
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      #   - name: Deploy report to Github Pages
      #     if: always()
      #     uses: peaceiris/actions-gh-pages@v2
      #     env:
      #       PERSONAL_TOKEN: ${{ secrets.TOKEN }}
      #       PUBLISH_BRANCH: gh-pages
      #       PUBLISH_DIR: allure-history