name: CI

on:
  push:
    branches: [main]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Npm install
        run: npm ci

      - name: Npx run
        run: npx cypress run --headless

      - name: Allure run
        run: npm run mytest

      - name: Allure report run
        run: npm run test

      - name: Create test summary
        uses: test-summary/action@v1.0
        if: always()
        with:
          paths: reports/*.xml

      - name: Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots