# name: CI
# on: [push, pull_request]
# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       # Install npm dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v5

#       - name: Run Cypress
#         continue-on-error: true
#         run: npm run cy:run

#       - name: Get Allure history
#           uses: actions/checkout@v3
#             if: always()
#               continue-on-error: true
#               with:
#                 ref: allure
#                 path: allure

#             - name: Generate Allure Report
#               uses: simple-elf/allure-report-action@master
#               if: always()
#               with:
#                   allure_results: allure-results
#                   gh_pages: allure

#             - name: Deploy report to Github Pages
#               if: always()
#               uses: peaceiris/actions-gh-pages@v3
#               with:
#                   github_token: ${{ secrets.GITHUB_TOKEN }}
#                   publish_branch: allure
#                   publish_dir: allure-history

# name: CI
# on: [push, pull_request]
# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       # Install npm dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v5

name: Cypress Tests with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests and generate Allure report
        run: npx cypress run --record --parallel --group "Allure" --env allure=true

      - name: Archive Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
